### PR TITLE
Set-ADSIUser

### PR DESCRIPTION
**Pull request by MickyBalladelli**
Implementation of Set-ADSIUser

### CODE REVIEW

**Comment by MickyBalladelli** [comment]
Fixed conflict

**Comment by MickyBalladelli** [comment]
Sure, I wasn't sure if the conflict came from there. The guid does not need to be changed.

**Comment by lazywinadmin** [comment]
Honnetement je ne vois pas d'ou viens le probleme :-/

**Comment by MickyBalladelli** [comment]
je pense savoir d'ou ça vient

**Pull request closed without merging**
